// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuJAQaG6tlSZXNVBL6azdPdutr9vHuCuc',
    appId: '1:1052373662813:web:5a7fb7ac90e4df1b9ce1b4',
    messagingSenderId: '1052373662813',
    projectId: 'c-ecommerce-c704c',
    authDomain: 'c-ecommerce-c704c.firebaseapp.com',
    storageBucket: 'c-ecommerce-c704c.appspot.com',
    measurementId: 'G-9VMMXDNS7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARLrL36GBNBKmrrvFhXihaiC1HagnnNRI',
    appId: '1:1052373662813:android:fa80e2cbffa3fcef9ce1b4',
    messagingSenderId: '1052373662813',
    projectId: 'c-ecommerce-c704c',
    storageBucket: 'c-ecommerce-c704c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMlvS1q6gNSlmcQ5b6oBIqU1osmXReLbg',
    appId: '1:1052373662813:ios:7b728ff01e25a32c9ce1b4',
    messagingSenderId: '1052373662813',
    projectId: 'c-ecommerce-c704c',
    storageBucket: 'c-ecommerce-c704c.appspot.com',
    androidClientId: '1052373662813-tjqtnq3t5uj2qc82936nj0irf9atajvo.apps.googleusercontent.com',
    iosClientId: '1052373662813-0hn2opigtvqhkeib5du75igms0op71rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.duaraEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMlvS1q6gNSlmcQ5b6oBIqU1osmXReLbg',
    appId: '1:1052373662813:ios:7b728ff01e25a32c9ce1b4',
    messagingSenderId: '1052373662813',
    projectId: 'c-ecommerce-c704c',
    storageBucket: 'c-ecommerce-c704c.appspot.com',
    androidClientId: '1052373662813-tjqtnq3t5uj2qc82936nj0irf9atajvo.apps.googleusercontent.com',
    iosClientId: '1052373662813-0hn2opigtvqhkeib5du75igms0op71rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.duaraEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuJAQaG6tlSZXNVBL6azdPdutr9vHuCuc',
    appId: '1:1052373662813:web:c0744017a392740d9ce1b4',
    messagingSenderId: '1052373662813',
    projectId: 'c-ecommerce-c704c',
    authDomain: 'c-ecommerce-c704c.firebaseapp.com',
    storageBucket: 'c-ecommerce-c704c.appspot.com',
    measurementId: 'G-6N81RL415H',
  );

}